apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nexusrepos.sonatype.com
spec:
  group: sonatype.com
  names:
    kind: NexusRepo
    listKind: NexusRepoList
    plural: nexusrepos
    singular: nexusrepo
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
